name: miapp_flutter1
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^2.1.0 


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/nodis.png
    - assets/cowmap.png
    - assets/carneSignUp.webp
    - assets/Locations.png
    - assets/crudemeat.jpg
    - assets/bife.jpg
    - assets/churrasco.jpg
    - assets/postregenerico.jpg
    - assets/puntaanca.jpg
    - assets/tbone.jpeg
    - assets/vinogenerico.jpg
    - assets/raw.jpg
    - assets/romanmeat.jpg
    - assets/noreserva.jpeg
    - assets/noreservas.png
    - assets/closed.jpg
    - assets/pse.png
    - assets/p1.jpg
    - assets/p2.jpg
    - assets/p3.jpg
    - assets/co2.webp
